# Generated by Django 3.1.4 on 2021-02-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decode_Pesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_uji', models.CharField(max_length=150)),
                ('nama_video', models.CharField(max_length=150)),
                ('nama_pengujian', models.CharField(max_length=150)),
                ('rsa_public', models.CharField(max_length=150)),
                ('rsa_crt', models.CharField(max_length=150)),
                ('a_value', models.IntegerField()),
                ('c_value', models.IntegerField()),
                ('m_value', models.IntegerField()),
                ('x_0', models.CharField(max_length=150)),
                ('crt_value', models.FloatField()),
                ('waktu_pengujian', models.DateTimeField()),
                ('message_decode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Encode_Pesan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_uji', models.CharField(max_length=150)),
                ('nama_video', models.CharField(max_length=150)),
                ('nama_pengujian', models.CharField(max_length=150)),
                ('rsa', models.CharField(max_length=150)),
                ('rsa_crt', models.CharField(max_length=150)),
                ('a_value', models.IntegerField()),
                ('c_value', models.IntegerField()),
                ('m_value', models.IntegerField()),
                ('x_0', models.CharField(max_length=150)),
                ('crt_value', models.FloatField()),
                ('waktu_pengujian', models.DateTimeField()),
                ('message_encode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Proses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_uji', models.CharField(max_length=150)),
                ('frame', models.CharField(max_length=10)),
                ('hash_data', models.CharField(max_length=200)),
            ],
        ),
    ]
