# Generated by Django 3.1.4 on 2021-03-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunci_RSA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_kunci', models.CharField(max_length=150)),
                ('kunci', models.CharField(max_length=150)),
                ('active', models.CharField(max_length=150)),
            ],
        ),
    ]
